### PR TITLE
Add Makefile with some tooling + tags in setup.py

### PR DESCRIPTION
**Pull request by sylvinus**
flake8 is reporting some stuff to fix :)

```
(venv) ➜  tunacell git:(master) make flake8
venv/bin/flake8 tuna
tuna/parser.py:592:46: E221 multiple spaces before operator
tuna/base/cell.py:400:9: F841 local variable '_' is assigned to but never used
tuna/base/container.py:576:28: E225 missing whitespace around operator
tuna/base/container.py:583:28: E225 missing whitespace around operator
tuna/base/experiment.py:98:23: E241 multiple spaces after ','
tuna/base/experiment.py:354:13: F841 local variable 'lineages' is assigned to but never used
tuna/base/lineage.py:195:21: F841 local variable '_' is assigned to but never used
tuna/plotting/dynamics.py:285:29: E225 missing whitespace around operator
tuna/plotting/dynamics.py:452:1: C901 'plot_stationary' is too complex (43)
tuna/plotting/dynamics.py:660:57: F812 list comprehension redefines 'ob' from line 633
tuna/plotting/samples.py:219:1: C901 'plot_samples' is too complex (63)
tuna/plotting/samples.py:647:49: E241 multiple spaces after ','
tuna/plotting/statics.py:116:30: E241 multiple spaces after ','
tuna/plotting/statics.py:157:34: E241 multiple spaces after ','
tuna/plotting/timeseries.py:52:1: C901 'add_timeseries' is too complex (33)
tuna/stats/api.py:119:9: E129 visually indented line with same indent as next logical line
tuna/stats/compute.py:493:45: E241 multiple spaces after ','
tuna/stats/compute.py:675:45: E241 multiple spaces after ','
tuna/stats/utils.py:194:5: E129 visually indented line with same indent as next logical line
tuna/tests/test_io_text.py:34:9: F841 local variable '_' is assigned to but never used
tuna/tests/test_observable.py:74:13: F841 local variable '_' is assigned to but never used
```

### CODE REVIEW

**Review by LeBarbouze — APPROVED** [review]
Idoine

**Comment by LeBarbouze** [comment]
Hey @sylvinus I have a flake8 error :

```venv/bin/flake8 tuna
tuna/parser.py:592:46: E221 multiple spaces before operator
tuna/stats/compute.py:493:45: E241 multiple spaces after ','
tuna/stats/compute.py:675:45: E241 multiple spaces after ','
tuna/stats/utils.py:194:5: E129 visually indented line with same indent as next logical line
tuna/stats/api.py:119:9: E129 visually indented line with same indent as next logical line
tuna/tests/test_io_text.py:34:9: F841 local variable '_' is assigned to but never used
tuna/tests/test_observable.py:74:13: F841 local variable '_' is assigned to but never used
tuna/base/cell.py:400:9: F841 local variable '_' is assigned to but never used
tuna/base/container.py:576:28: E225 missing whitespace around operator
tuna/base/container.py:583:28: E225 missing whitespace around operator
tuna/base/experiment.py:98:23: E241 multiple spaces after ','
tuna/base/experiment.py:354:13: F841 local variable 'lineages' is assigned to but never used
tuna/base/lineage.py:195:21: F841 local variable '_' is assigned to but never used
tuna/plotting/dynamics.py:285:29: E225 missing whitespace around operator
tuna/plotting/dynamics.py:452:1: C901 'plot_stationary' is too complex (43)
tuna/plotting/dynamics.py:660:57: F812 list comprehension redefines 'ob' from line 633
tuna/plotting/samples.py:219:1: C901 'plot_samples' is too complex (63)
tuna/plotting/samples.py:647:49: E241 multiple spaces after ','
tuna/plotting/timeseries.py:52:1: C901 'add_timeseries' is too complex (33)
tuna/plotting/statics.py:116:30: E241 multiple spaces after ','
tuna/plotting/statics.py:157:34: E241 multiple spaces after ','
Makefile:9 : la recette pour la cible « flake8 » a échouée
make: *** [flake8] Erreur 1
```

Any clue ?

**Comment by sylvinus** [comment]
@LeBarbouze well the goal is to fix every one of them (or to disable the rules you don't like in the .flake8, but I've already done it for a few of them)

**Comment by LeBarbouze** [comment]
Yes I got that, I was wondering about the make error. I thought something wrong happened with flake8 but executing flake8 directly goes well. I guess this is a make specific thing, maybe because flake8 is returning a non-regular value to make ? (this is the first time I used make...) Anyways, a big thank you @sylvinus !

**Pull request merged**
